'use client'

import { useState, useEffect } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { ThemeToggle } from '@/components/theme-toggle'
import { Twitter, Download, Home, Share2, Sparkles } from 'lucide-react'
import Link from 'next/link'

interface ShareCardProps {
  cardId: string
}

export function ShareCard({ cardId }: ShareCardProps) {
  // Mock data - in real app, fetch from database using cardId
  const cardData = {
    handle: '@example',
    auraScore: 87,
    tierName: 'Digital Wizard',
    dominantTopic: 'AI & Tech',
    sentiment: 'Positive',
    engagement: 'High',
    viralScore: 92
  }

  const shareOnTwitter = () => {
    const tweetText = `Just discovered my digital aura! Check out your Aura Score on @AuraCardAI 🌈`
    const shareUrl = window.location.href
    const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(tweetText)}&url=${encodeURIComponent(shareUrl)}`
    window.open(twitterUrl, '_blank')
  }

  const downloadCard = () => {
    const link = document.createElement('a')
    link.href = `/api/og/${cardId}`
    link.download = 'aura-card.png'
    link.click()
  }

  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Background Pattern */}
      <div className="absolute inset-0 grid-pattern opacity-30" />
      
      {/* Floating Elements */}
      <div className="absolute top-20 left-20 w-24 h-24 bg-neo-primary border-4 border-black dark:border-white rotate-12 opacity-20" />
      <div className="absolute bottom-32 right-32 w-32 h-32 bg-neo-secondary border-4 border-black dark:border-white -rotate-12 opacity-20" />
      
      <div className="relative z-10 container mx-auto px-4 py-8">
        {/* Header */}
        <div className="flex justify-between items-center mb-8">
          <Link href="/">
            <Button className="neobrutalist-button">
              <Home className="mr-2 h-4 w-4" />
              BACK TO HOME
            </Button>
          </Link>
          <ThemeToggle />
        </div>

        <div className="max-w-2xl mx-auto text-center">
          {/* Title */}
          <div className="neobrutalist-card p-6 mb-8 bg-neo-primary inline-block">
            <h1 className="text-4xl font-black text-black flex items-center">
              <Sparkles className="mr-3 h-8 w-8" />
              AURA CARD
            </h1>
          </div>

          {/* Aura Card Display */}
          <Card className="neobrutalist-card mb-8 bg-gradient-to-br from-neo-primary via-neo-accent to-neo-purple p-2">
            <CardContent className="neobrutalist-card bg-white dark:bg-black p-8 text-center">
              <div className="mb-6">
                <div className="text-3xl font-black mb-4">{cardData.handle}</div>
                <div className="text-7xl font-black text-neo-primary mb-4 font-mono">{cardData.auraScore}</div>
                <div className="neobrutalist-badge bg-neo-secondary text-white text-xl font-black px-6 py-3 mb-6">
                  {cardData.tierName}
                </div>
              </div>
              
              <div className="grid grid-cols-2 gap-4 mb-6">
                <div className="neobrutalist-badge bg-neo-accent text-white px-4 py-2">
                  {cardData.dominantTopic}
                </div>
                <div className="neobrutalist-badge bg-neo-warning text-black px-4 py-2">
                  {cardData.sentiment}
                </div>
                <div className="neobrutalist-badge bg-neo-purple text-white px-4 py-2">
                  {cardData.engagement} ENGAGEMENT
                </div>
                <div className="neobrutalist-badge bg-neo-secondary text-white px-4 py-2">
                  {cardData.viralScore}% VIRAL
                </div>
              </div>
              
              <div className="text-sm font-bold text-muted-foreground">
                GENERATED BY AURA CARD AI
              </div>
            </CardContent>
          </Card>

          {/* Action Buttons */}
          <div className="flex gap-4 justify-center mb-8">
            <Button
              onClick={shareOnTwitter}
              className="neobrutalist-button-primary px-8 py-4"
            >
              <Twitter className="mr-2 h-5 w-5" />
              SHARE ON X
            </Button>
            <Button
              onClick={downloadCard}
              className="neobrutalist-button px-8 py-4"
            >
              <Download className="mr-2 h-5 w-5" />
              DOWNLOAD
            </Button>
          </div>

          {/* CTA */}
          <div className="neobrutalist-card p-8 bg-gradient-to-r from-neo-secondary to-neo-purple">
            <h3 className="text-2xl font-black mb-4 text-white">
              WANT TO DISCOVER YOUR OWN DIGITAL AURA?
            </h3>
            <p className="text-lg font-bold text-white mb-6">
              JOIN THOUSANDS OF USERS ANALYZING THEIR DIGITAL PERSONAS
            </p>
            <Link href="/">
              <Button className="neobrutalist-button text-lg px-8 py-4 bg-white text-black hover:bg-gray-100">
                <Sparkles className="mr-2 h-5 w-5" />
                GET YOUR AURA CARD
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}
