

export default function TermsOfService() {
  return (
    <div className="bg-gray-900 min-h-screen py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto bg-gray-800 rounded-lg shadow-lg p-8">
        <h1 className="text-3xl font-bold text-white mb-4">
          Terms of Service for Auralytics
        </h1>
        <p className="text-sm text-gray-400 mb-8">
          Last Updated: August 7, 2025
        </p>

        <div className="space-y-6 text-gray-300">
          <p>
            Welcome to Auralytics! This is an experimental application created for the Puch AI Hackathon.
          </p>

          <div>
            <h2 className="text-xl font-semibold text-white mb-2">1. Service Description</h2>
            <p className="leading-relaxed">
              Auralytics is a tool for entertainment purposes that analyzes the last 200 public tweets of a user's X profile to generate a shareable "Aura Card."
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-white mb-2">2. Intended Use</h2>
            <p className="leading-relaxed">
              This app is intended for personal, non-commercial use. The functionality is provided as part of a time-limited hackathon and may change or be discontinued at any time.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-white mb-2">3. Disclaimer</h2>
            <p className="leading-relaxed">
              The service is provided "as-is" without any warranties. The analysis is generated by an AI and may not be accurate, complete, or suitable for any purpose. You agree to use this service at your own risk. We are not liable for any damages or harm related to your use of the application.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
